name: Build and release

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: 0.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.1"

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r script/requirements.txt

      - name: Get version
        id: get-version
        run: echo "::set-output name=version::$(node -p 'require(\"./package.json\").version')"

      - name: Update version
        run: python script/update_version.py release $VERSION package.json

      - name: Validate TypeScript syntax
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build Docker image
        run: |
          docker build -t my-image .
          docker tag my-image my-registry/my-image:${VERSION}
          docker push my-registry/my-image:${VERSION}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update version to v${VERSION}"
          commit_options: "--no-verify"
