name: Pull Request Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Validate TypeScript syntax
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build code
        run: yarn build
